CREATE DATABASE IF NOT EXISTS afy CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE afy;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  display_name VARCHAR(160) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','AGENT') NOT NULL DEFAULT 'AGENT',
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS frigos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  capacite INT NOT NULL DEFAULT 10,
  etat ENUM('FONCTIONNEL','PRESQUE_COMPLET','COMPLET','EN_PANNE') NOT NULL DEFAULT 'FONCTIONNEL',
  derniere_verification DATETIME NULL,
  derniere_maintenance DATETIME NULL,
  prochaine_maintenance DATETIME NULL,
  observations TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deces (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  numero VARCHAR(80) NOT NULL UNIQUE,
  anonyme TINYINT(1) NOT NULL DEFAULT 0,
  nom VARCHAR(160) NULL,
  prenom VARCHAR(160) NULL,
  cin VARCHAR(80) NULL,
  sexe ENUM('MASCULIN','FEMININ','INDETERMINE') NOT NULL DEFAULT 'INDETERMINE',
  age_inconnu TINYINT(1) NOT NULL DEFAULT 0,
  age INT NULL,
  date_entree DATETIME NOT NULL,
  service_origine VARCHAR(180) NULL,
  mode_arrivee VARCHAR(120) NULL,
  frigo_id BIGINT UNSIGNED NULL,
  observations_entree TEXT NULL,
  date_sortie DATETIME NULL,
  destination VARCHAR(180) NULL,
  ambulance VARCHAR(120) NULL,
  numero_inhumation VARCHAR(120) NULL,
  observations_sortie TEXT NULL,
  statut ENUM('PRESENT','SORTI') NOT NULL DEFAULT 'PRESENT',
  archive TINYINT(1) NOT NULL DEFAULT 0,
  agent_entree_id BIGINT UNSIGNED NULL,
  agent_sortie_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_deces_frigo FOREIGN KEY (frigo_id) REFERENCES frigos(id) ON DELETE SET NULL,
  CONSTRAINT fk_deces_agent_entree FOREIGN KEY (agent_entree_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_deces_agent_sortie FOREIGN KEY (agent_sortie_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_deces_statut (statut),
  INDEX idx_deces_archive (archive),
  INDEX idx_deces_date_entree (date_entree)
);

CREATE TABLE IF NOT EXISTS prise_en_charge (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  deces_id BIGINT UNSIGNED NOT NULL UNIQUE,
  type ENUM('FAMILLE','ASSOCIATION','ORGANISME','INSTITUTION','AUTRE','NON_DEFINIE') NOT NULL DEFAULT 'NON_DEFINIE',
  nom_responsable VARCHAR(180) NULL,
  date_prise_en_charge DATETIME NULL,
  contact VARCHAR(120) NULL,
  observations TEXT NULL,
  statut ENUM('A_DEFINIR','EN_ATTENTE','CONFIRMEE','EN_COURS','TERMINEE') NOT NULL DEFAULT 'A_DEFINIR',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pec_deces FOREIGN KEY (deces_id) REFERENCES deces(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS materiels (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(180) NOT NULL,
  type VARCHAR(120) NULL,
  reference VARCHAR(120) NULL,
  frigo_id BIGINT UNSIGNED NULL,
  statut ENUM('FONCTIONNEL','EN_PANNE','INTERVENTION_EN_ATTENTE','EN_MAINTENANCE','REPARE') NOT NULL DEFAULT 'FONCTIONNEL',
  date_mise_service DATE NULL,
  derniere_maintenance DATETIME NULL,
  prochaine_maintenance DATETIME NULL,
  probleme TEXT NULL,
  date_intervention DATETIME NULL,
  responsable_intervention VARCHAR(180) NULL,
  resultat_intervention TEXT NULL,
  observations TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_materiel_frigo FOREIGN KEY (frigo_id) REFERENCES frigos(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS parametres (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cle VARCHAR(120) NOT NULL UNIQUE,
  valeur TEXT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT UNSIGNED NULL,
  user_name VARCHAR(160) NULL,
  role VARCHAR(40) NULL,
  action VARCHAR(100) NOT NULL,
  deces_id BIGINT UNSIGNED NULL,
  deces_numero VARCHAR(80) NULL,
  details JSON NULL,
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_audit_created (created_at)
);
